[http.middlewares.simpleAuth.basicAuth]
  users = [
    "admin:$apr1$px73qT07$6MLHNwmn8GQu16nbQmcFU."
  ]

[http.routers.api]
  rule = "Host(`monitor.localhost`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"
