# Use the official Redis Docker image as the base image
FROM redis:latest

# Set the persistence option
VOLUME /data

# Expose the Redis port
EXPOSE 6379

# Start the Redis server
CMD ["redis-server"]
